### ISSUE TITLE
Error in default kanna flame settings

### ISSUE THREAD

**Issue by florianhumblot** [StarLinez/StarLinez.github.io#1]
In the kanna settings for flame stats the current multiplier for hp/mp is set to `0.014285`
I believe this is a typo and should be `0.0014286` (one more zero after the dot).
This because `1 / 700 = 0.00142857`  

I confirmed the issue by navigating to the calculator in  incognito mode too :)

**Comment by GillesThewissen** [comment]
Bit late of a response to close the issue but:
The guide the scoring is based on states the weight of HP for Kanna's is 1/70 which translates to a multiplier of 0.014285 meaning it isn't a bug.
