### ISSUE TITLE
Change Guild Activities Reset Day

### ISSUE THREAD

**Issue by kaizerfreak** [StarLinez/StarLinez.github.io#2]
Culvert, Flag Race, and Buffs were changed to reset on Thursday UTC with patch v253

https://www.nexon.com/maplestory/news/update/18317/updated-9-29-v-253-maple-story-x-bugcat-capoo-patch-notes#GuildSystemImprovements

**Comment by StarLinez** [comment]
Been working on a rework of the dailies&weeklies tracker so I plan to implement these changes once that is done (although it's taken longer than expected to find time for this)

**Comment by StarLinez** [comment]
Rework is available just not yet fully live :) 
https://starlinez.github.io/games/maplestory/tracker/weekly

**Comment by kaizerfreak** [comment]
Wow, very slick!
