### ISSUE TITLE
Import/Export/Clear function missing Sacred Symbols

### ISSUE THREAD

**Issue by JustinBrow** [StarLinez/starlinez.github.io#4]
![image](https://github.com/user-attachments/assets/94ba1cf3-7130-4b36-ac35-bac0d082c540)
![image](https://github.com/user-attachments/assets/509b55cc-0cfa-4bf7-add0-a97bf65cee5a)
![image](https://github.com/user-attachments/assets/09b08264-052d-4a4a-881a-064d419e5643)

**Comment by JustinBrow** [comment]
This is also missing sacredSymbolSaveDatav3
```
constructor(s, r) {
   this.titleService = s,
   this.metaService = r,
   this.settingsData = {
      dailiesDataV3: "",
      weekliesDataV3: "",
      arcaneSymbolSaveDataV2: "",
      flameData: "",
      weaponFlameData: ""
   }
}
```

**Comment by StarLinez** [comment]
Fix for this will go live in less than an hour (overlooked this a long time ago)
