### ISSUE TITLE
Import/export JSON format

### ISSUE THREAD

**Issue by JustinBrow** [StarLinez/StarLinez.github.io#7]
While the current import/export functions work. The nested JSON exported does not prettify. This can be addressed by parsing/stringifying the nested JSON into/out of localStorage during the export/import.  
Here is an example of what I propose. This would be applied to each settingsData to be exported/imported.  
Current export function:  
```
localStorage.getItem("dailiesDataV3") && (this.settingsData.dailiesDataV3 = localStorage.getItem("dailiesDataV3")),
```
Suggested export function:  
```
localStorage.getItem("dailiesDataV3") && (this.settingsData.dailiesDataV3 =  JSON.parse(localStorage.getItem("dailiesDataV3"))),
```
Current import function:  
```
this.settingsData.dailiesDataV3 && localStorage.setItem("dailiesDataV3", this.settingsData.dailiesDataV3),
```
Suggested import function:  
```
this.settingsData.dailiesDataV3 && localStorage.setItem("dailiesDataV3", JSON.stringify(this.settingsData.dailiesDataV3)),
```
Attached is an example of the JSON export with the suggested changes.
[MapleTrackerSettings.json](https://github.com/user-attachments/files/17737075/MapleTrackerSettings.json)

**Comment by JustinBrow** [comment]
If you pretty print the JSON here is a visual before/after representation.
Before:  
![image](https://github.com/user-attachments/assets/fde26269-58de-4f41-8b70-3b0bc67eb84f)
After:  
![image](https://github.com/user-attachments/assets/fff7ee0b-ddfb-4f4b-b2c3-82800c5c4762)

**Comment by StarLinez** [comment]
Ah I see what you mean with the current version having \"instead of just a ".
Implemented the suggestion , might rework how this all works in the future as I'm working on a rework of the dailies&weeklies tracker which works with a generaldata storage object.

**Comment by JustinBrow** [comment]
Something I just considered. This is a breaking change as the old JSON format can't be imported by the changed function.

**Comment by StarLinez** [comment]
Ah true might revert until I rework it completely and have all old exports be irrelevant
